# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:  
      matrix:  
        goos: [windows, darwin, linux]  
        goarch: [amd64, arm64]     
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Install dependencies
      run: |
        go get .
        
    - name: Build
      env:  
        GOOS: ${{ matrix.goos }}  
        GOARCH: ${{ matrix.goarch }}  
      run: |
        go build -v ./...
        mv verandom.exe "${{ matrix.goos }}_${{ matrix.goarch }}_verandom.exe" || true
        mv verandom "${{ matrix.goos }}_${{ matrix.goarch }}_verandom" || true

#    - name: Test
#      run: go test -v ./...
