# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:  
      matrix:  
        goos: [windows, darwin, linux]  
        goarch: [amd64, arm64]     
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Install dependencies
      run: |
        go get .
        
    - name: Build
      env:  
        GOOS: ${{ matrix.goos }}  
        GOARCH: ${{ matrix.goarch }}  
      run: |
        if [ $GOOS = "windows" ]; then export BINARY_SUFFIX="$BINARY_SUFFIX.exe"; fi
        go build -v ./...
        mkdir output/ || true
        mv verandom$BINARY_SUFFIX output/"${{ matrix.goos }}_${{ matrix.goarch }}_verandom$BINARY_SUFFIX"

#    - name: Test
#      run: go test -v ./...

    - name: Upload artifacts  
      uses: actions/upload-artifact@v4  
      with:  
        name: ${{ matrix.goos }}_${{ matrix.goarch }}_verandom
        path: output/  
